### PR TITLE
Add: Hill Cipher

### PR DESCRIPTION
**Pull request by Swarley-hax**
added Hill cipher implementation in rust and updated README.md

### CODE REVIEW

**Comment by Swarley-hax** [comment]
is this repo participating in HacktoberFest 21 as a maintainer?

**Review by zolagonano — APPROVED** [review]

**Comment by zolagonano** [comment]
> added Hill cipher implementation in rust and updated README.md

Thanks :)

> is this repo participating in HacktoberFest 21 as a maintainer?

Yeah, it is :)

**Comment by zolagonano** [comment]
I can't find the crate matrix, what did you use to multiply matrices? @Swarley-hax

**Comment by zolagonano** [comment]
I think i have to remove hill cipher till i find the crate you used to multiply matrices or rewrite it with another linear algebra library, but thanks for your contribution :)

**Pull request merged**
